name: OniLPCraft
version: ${project.version}
main: fr.edenskull.onilpcraft.OniLPCraft
api-version: 1.13
authors: [Edenskull]
description: Plugin for basics LP Commands
commands:
  lp:
    description: This command will give you the basic stuff for a Let's Play
    usage: "Usage: /<lp>"
  clearchunk:
    description: This command will erase a whole chunk to from the bedrock to the sky
    usage: "Usage: /<clearchunk>"
